<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Data</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>2e58ad77-94b9-4c55-846c-311b50ea1423</testSuiteGuid>
   <testCaseLink>
      <guid>127ad33d-0b65-4da1-a579-28d7b554fe85</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>16fa0515-24b9-4140-b005-dfc295d62398</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>16fa0515-24b9-4140-b005-dfc295d62398</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>2d86fc42-3d1b-4baf-a4ce-d9764f8ca8c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>16fa0515-24b9-4140-b005-dfc295d62398</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>0b48d3ea-6ab1-4091-b2ae-e459f4340afe</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
