<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_TP-PRO-91469</name>
   <tag></tag>
   <elementGuidId>917f22da-b329-4f40-97f9-9901fe00f515</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='ctl00_CPH2_rgUnits_ctl00__0']/td[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_CPH2_rgUnits_ctl00__0 > td:nth-of-type(6)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;TP-PRO-91469&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>98123d65-d7c2-4030-9e75-8a15af4d86c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TP-PRO-91469</value>
      <webElementGuid>4ca33550-24ed-44ba-856c-0f16c7830ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_CPH2_rgUnits_ctl00__0&quot;)/td[6]</value>
      <webElementGuid>20181c55-6f85-4760-996e-0b3e07922d01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ctl00_CPH2_rgUnits_ctl00__0']/td[6]</value>
      <webElementGuid>c3270989-e612-4612-bf47-3bd2731e8195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending'])[1]/following::td[4]</value>
      <webElementGuid>918bc761-cf03-4821-98b4-33c70d1d0f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::td[41]</value>
      <webElementGuid>8e61ce50-f6ed-4f8f-862a-b8155b252f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::td[1]</value>
      <webElementGuid>71fd6e0e-7afd-4082-aef8-d63da7540a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Z90'])[1]/preceding::td[7]</value>
      <webElementGuid>45b844e5-279e-4047-b00f-9241793290c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TP-PRO-91469']/parent::*</value>
      <webElementGuid>47fe2319-9a3c-4a7c-a21e-e14e5102999a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td[6]</value>
      <webElementGuid>97fecb6a-d2d1-48a6-9626-806bff3d8a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'TP-PRO-91469' or . = 'TP-PRO-91469')]</value>
      <webElementGuid>f9afc2a2-32bb-4c4b-a8fb-2f72ee67a8f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
